version: '3.8'

services: 

  localstack:
    image: localstack/localstack:latest
    environment: 
      - AWS_DEFAULT_REGION=ap-southeast-1
      - EDGE_PORT=4566
      - SERVICES=lambda,s3,dynamodb,iam
      - HOSTNAME_EXTERNAL=localstack
      - DEBUG=1
    ports: 
      - '4566:4566'
      - '8080:8080'
    volumes: 
      - "${TEMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"