name: Poetry, Pylint, Pytest, Terraform

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack:latest
        env:
          SERVICES: cloudformation,iam,sts,ssm,s3,cloudwatch,cloudwatch-logs,lambda,dynamodb,apigateway
          DEFAULT_REGION: ap-southeast-1
          AWS_ACCESS_KEY_ID: mock_access_key
          AWS_SECRET_ACCESS_KEY: mock_secret_key
        ports:
          - 4566:4566
          - 4571:4571

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: Install Poetry Action
      uses: snok/install-poetry@v1.3.1
      with:
          virtualenvs-create: true
          virtualenvs-in-project: true

    - name: Cache Poetry virtualenv
      uses: actions/cache@v2
      with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

    - name: Analysing the code with pylint
      run: |
        poetry run pylint --rcfile=pylintrc src/
    
    - name: Run with pytest
      run: |
        poetry run pytest --cov=src --cov-fail-under=100 tests/

    - uses: hashicorp/setup-terraform@v1
    - name: Terraform init
      run: |
        terraform -chdir=terraform/ init
    
    - name: Terraform validate
      run: |
        terraform -chdir=terraform/ validate
    
    - name: Terraform plan
      run: |
        terraform -chdir=terraform/ plan

    - name: Terraform apply
      run: |
        terraform -chdir=terraform/ apply --auto-approve
